
name: Olympix Security 
on: 
  workflow_call:
    secrets:
      OLYMPIX_API_TOKEN:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout (Reusable)
        uses: actions/checkout@v3
        with: 
          repository: pthakur-circle/integrate-repo
          path: ./integrate-repo
      
      - name: List
        run: ls -al ./integrate-repo

      - name: Read arguments from file
        id: read_args
        run: |
          args=$(awk '{print "--no-" $1}' ./integrate-repo/rule.txt | tr '\n' ' ')
          echo "args=$args" >> $GITHUB_ENV

      - name: Run Olympix Integrated Security
        uses: olympix/integrated-security@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
          required: true
        with: 
          args: ${{ env.args }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: olympix.sarif
