
name: Olympix Security 
on: 
  workflow_call:
    secrets:
      OLYMPIX_API_TOKEN:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List directory
        run: ls -alh

      - name: Read arguments from file
        id: read_args
        run: |
          args=$(awk '{print "--no-" $1}' custome_olympix_rule.txt | tr '\n' ' ')
          echo "args=$args" >> $GITHUB_ENV

      - name: Run Olympix Integrated Security
        uses: olympix/integrated-security@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
          required: true
        with: ${{ env.args }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: olympix.sarif
