name: Reusable workflow
'on':
  workflow_call: null
jobs:
  rul1-job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write something to log
        run: |
          echo "Reusable workflow one"
