name: Olympix Security 
on: 
  workflow_call:
    secrets:
      OLYMPIX_API_TOKEN:
        required: true

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout (Reusable)
        uses: actions/checkout@v3
        with: 
          repository: pthakur-circle/integrate-repo
          path: ./integrate-repo

      # - name: Read arguments from file
      #   id: read_args
      #   run: |
      #     REPO_NAME="${{ github.repository }}"
      #     ARGS=$(awk -v repo="$REPO_NAME" '$1 == repo { $1 = ""; print $0 }' ./integrate-repo/rule.txt | tr '\n' ' ')
      #     if [ -z "$ARGS" ]; then
      #       echo "No arg found for $REPO_NAME"
      #       ARGS=""
      #     else
      #       echo "Args found for $REPO_NAME: $ARGS"
      #     fi
      #     echo "args=${ARGS}" >> $GITHUB_ENV

      - name: Read arguments from file
        id: read_args
        run: |
          REPO_NAME="${{ github.repository }}"
          ARGS=$(jq -r --args repo "$REPO_NAME" '.[$repo] // empty | join(" ")' ./integrate-repo/rule.json)
          if [ "$ARGS" = "null" ]; then
            echo "No args"
          else
            echo "Args for $REPO_NAME: $ARGS"
          fi
          echo "args=$ARGS" >> $GITHUB_ENV

      - name: Debug-Print args
        run: echo "Args = ${{ env.args }}"

      - name: Run Olympix Integrated Security
        id: run_olympix
        uses: olympix/integrated-security@main
        env:
          OLYMPIX_API_TOKEN: ${{ secrets.OLYMPIX_API_TOKEN }}
          required: true
        with: 
          args: -f sarif -o ./integrate-repo ${{ env.args }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./integrate-repo/olympix.sarif
