name: Reusable workflow
'on':
  workflow_call: 
    secrets: 
      OLYMPIX_API_TOKEN: 
        required: true
jobs:
  rul1-job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with: 
          repo-token: ${{ secrets.OLYMPIX_API_TOKEN }}
